# Generated by Django 5.2.4 on 2025-08-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0002_remove_motorcycle_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='location',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='longitude',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorcycle', to='oman_app.cities'),
        ),
    ]
