# Generated by Django 5.2.4 on 2025-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0003_remove_motorcycle_cities_remove_motorcycle_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='body_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('budgy', 'Budgy'), ('cruiser', 'Cruiser'), ('offroad', 'Offroad'), ('scooter', 'Scooter'), ('sport', 'Sport'), ('street', 'Street'), ('tricycle', 'Tricycle'), ('other', 'Other')], max_length=50, verbose_name='Car Body Type'),
        ),
    ]
