# Generated by Django 5.2.4 on 2025-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0004_alter_motorcycle_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='kilometers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometers'),
        ),
    ]
