# Generated by Django 5.2.4 on 2025-08-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0005_motorcycle_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
    ]
