# Generated by Django 5.2.4 on 2025-08-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0006_motorcycle_rental_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='name',
        ),
    ]
