# Generated by Django 5.2.4 on 2025-08-03 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0007_remove_motorcycle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Scooter/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ScooterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Scooter/videos/', verbose_name='Video')),
            ],
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine Capacity (cc)'),
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(max_length=100, verbose_name='Year of Manufacture')),
                ('description', models.TextField(verbose_name='Description')),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometers')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], default='cash', max_length=20, null=True, verbose_name='Payment Method')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('engine_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine Capacity (cc)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10, verbose_name='Condition')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('rental_period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scooter', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scooter', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='scooter', to='oman_app.scooterimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='scooter', to='oman_app.scootervideo', verbose_name='Videos')),
            ],
        ),
    ]
