# Generated by Django 5.2.4 on 2025-08-03 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0008_scooterimage_scootervideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadbikesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Quadbikes/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='QuadbikesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Quadbikes/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Quadbikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(verbose_name='Description')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], default='cash', max_length=20, null=True, verbose_name='Payment Method')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10, verbose_name='Condition')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('rental_period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadbikes', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadbikes', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='quadbikes', to='oman_app.quadbikesimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='quadbikes', to='oman_app.quadbikesvideo', verbose_name='Videos')),
            ],
        ),
    ]
