# Generated by Django 5.2.4 on 2025-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0010_helmetclothesimage_helmetclothesvideo_helmetclothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmetclothes',
            name='product_type',
            field=models.CharField(choices=[('helmet', 'Helmet'), ('clothes', 'Clothes')], default='sell', max_length=10, verbose_name='Product Type'),
        ),
    ]
