# Generated by Django 5.2.4 on 2025-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0011_helmetclothes_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helmetclothes',
            old_name='product_type',
            new_name='helmetcloth_type',
        ),
        migrations.AddField(
            model_name='helmetclothes',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helmetclothes',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadbikes',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadbikes',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scooter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scooter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
