# Generated by Django 5.2.4 on 2025-08-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0012_rename_product_type_helmetclothes_helmetcloth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='lister_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('dealer', 'Dealer')], default='dealer', max_length=10, verbose_name='Lister Type'),
        ),
        migrations.AddField(
            model_name='quadbikes',
            name='type',
            field=models.CharField(choices=[('quadbikes', 'Quad Bikes'), ('buggies', 'Buggies'), ('atv', 'ATV')], default='quadbikes', max_length=10, verbose_name='Product Type'),
        ),
    ]
