# Generated by Django 5.2.4 on 2025-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0013_motorcycle_lister_type_quadbikes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='lister_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('dealer', 'Dealer')], default='dealer', max_length=10, verbose_name='Lister Type'),
        ),
    ]
