# Generated by Django 5.2.4 on 2025-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0014_scooter_lister_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmetclothes',
            name='lister_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('dealer', 'Dealer')], default='dealer', max_length=10, verbose_name='Lister Type'),
        ),
        migrations.AlterField(
            model_name='helmetclothes',
            name='helmetcloth_type',
            field=models.CharField(choices=[('helmet', 'Helmet'), ('clothes', 'Clothes')], default='helmet', max_length=10, verbose_name='Product Type'),
        ),
    ]
