# Generated by Django 5.2.4 on 2025-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0015_helmetclothes_lister_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=50, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='regional_spec',
            field=models.CharField(choices=[('gcc', 'GCC'), ('american', 'American'), ('canadian', 'Canadian'), ('euro', 'European'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese', 'Chinese'), ('other', 'Other')], default='gcc', max_length=20, verbose_name='Regional Specification'),
        ),
    ]
