# Generated by Django 5.2.4 on 2025-08-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0016_alter_automobile_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('does not apply', 'N/A')], default='yes', max_length=20, null=True, verbose_name='Warranty'),
        ),
    ]
