# Generated by Django 5.2.4 on 2025-08-07 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0017_alter_automobile_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunkCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='JunkCar/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='JunkCarVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='JunkCar/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='JunkCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('condition', models.CharField(choices=[('damaged', 'Damaged'), ('not_working', 'Not Working'), ('scrap', 'Scrap'), ('accident', 'Accident')], max_length=20, verbose_name='Condition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Price / Scrap Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junk_cars', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='junkcar', to='oman_app.junkcarimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='junkcar', to='oman_app.junkcarvideo', verbose_name='Videos')),
            ],
        ),
    ]
