# Generated by Django 5.2.4 on 2025-08-07 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0018_junkcarimage_junkcarvideo_junkcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='transmission',
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='bus_model',
            field=models.CharField(blank=True, help_text='Bus model (for buses)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='main_type',
            field=models.CharField(choices=[('trucks', 'Trucks'), ('buses', 'Buses'), ('forklifts', 'Forklifts'), ('trailers', 'Trailers'), ('cranes', 'Cranes'), ('tankers', 'Tankers'), ('parts_engines', 'Parts & Engines'), ('aircrafts', 'Aircrafts'), ('other', 'Other')], default='trucks', max_length=50),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Model (for trucks/trailers)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Rental period applicable if listing type is rent', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='sub_type',
            field=models.CharField(default='Cab-Chassis', max_length=100),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='heavyvehicle', to='oman_app.heavyvehicleimage'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='heavyvehicle', to='oman_app.heavyvehiclevideo'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='heavyvehicleimage',
            name='image',
            field=models.ImageField(upload_to='heavyvehicle/images/'),
        ),
        migrations.AlterField(
            model_name='heavyvehiclevideo',
            name='video',
            field=models.FileField(upload_to='heavyvehicle/videos/'),
        ),
    ]
