# Generated by Django 5.2.4 on 2025-08-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0019_remove_heavyvehicle_cities_remove_heavyvehicle_make_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='regions',
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_subtype',
            field=models.CharField(choices=[('fishing_boat', 'Fishing Boat'), ('luxury_yacht', 'Luxury Yacht'), ('stand_up_jet_ski', 'Stand-Up Jet Ski'), ('sit_down_jet_ski', 'Sit-Down Jet Ski'), ('paddle_boat', 'Paddle Boat'), ('kayak', 'Kayak'), ('canoe', 'Canoe'), ('other', 'Other')], default='fishing_boat', max_length=50, verbose_name='Subtype'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(choices=[('boats_yachts', 'Boats & Yachts'), ('jet_skis', 'Jet Skis'), ('paddle_kayak_other', 'Paddle Boats, Kayaks & Other')], default='boats_yachts', max_length=50, verbose_name='Boat Type'),
        ),
        migrations.AddField(
            model_name='boat',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='boat',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
