# Generated by Django 5.2.4 on 2025-08-07 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0020_remove_boat_cities_remove_boat_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiresAndCapsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tires_caps/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TiresAndCapsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='tires_caps/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='TiresAndCaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_type', models.CharField(choices=[('tyres', 'Tyres'), ('rims', 'Rims'), ('set_wheels_rims_tyres', 'Set of Wheels, Rims, and Tyres'), ('automotive_caps', 'Automotive Caps')], max_length=50)),
                ('size', models.CharField(blank=True, choices=[('10', '10'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('17.5', '17.5'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('22.5', '22.5'), ('23', '23'), ('25', '25'), ('30', '30'), ('other', 'Other')], max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('condition', models.CharField(choices=[('used', 'Used'), ('like_new', 'Like New')], max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='oman_app.tiresandcapsimage')),
                ('videos', models.ManyToManyField(blank=True, to='oman_app.tiresandcapsvideo')),
            ],
        ),
    ]
