# Generated by Django 5.2.4 on 2025-08-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0021_tiresandcapsimage_tiresandcapsvideo_tiresandcaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoaccessorypart',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='autoaccessorypart',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='autoaccessorypart',
            name='type',
        ),
        migrations.AddField(
            model_name='autoaccessorypart',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='autoaccessorypart',
            name='main_category',
            field=models.CharField(choices=[('car_parts', 'Car/4x4 Parts'), ('apparel_merch', 'Apparel, Merchandise & Accessories'), ('motorcycle_parts', 'Motorcycle Parts'), ('tools', 'Automotive Tools'), ('boat_parts', 'Boat Parts'), ('other_vehicle', 'Other Vehicle Parts')], default='car_parts', max_length=50),
        ),
        migrations.AddField(
            model_name='autoaccessorypart',
            name='sub_category',
            field=models.CharField(choices=[('wheels_tires', 'Wheels/Tires'), ('brakes', 'Brakes'), ('exterior_parts', 'Exterior Parts'), ('interior_parts', 'Interior Parts'), ('exhaust', 'Exhaust/Air Intake'), ('suspension', 'Suspension'), ('engine_computer', 'Engine & Computer Parts'), ('lighting', 'Lighting'), ('batteries', 'Batteries'), ('car_other', 'Other'), ('car_accessories', 'Car/4x4 Accessories'), ('apparel', 'Apparel'), ('motorcycle_accessories', 'Motorcycle Accessories'), ('merch_other', 'Other'), ('motorcycle_accessories', 'Accessories'), ('body_frame', 'Body & Frame'), ('engine_components', 'Engines & Components'), ('motorcycle_wheels', 'Wheels Tires'), ('tools', 'Automotive Tools'), ('boat_body', 'Body Parts & Accessories'), ('boat_engine', 'Engine Parts'), ('other_vehicle', 'Other Vehicle Parts')], default='wheels_tires', max_length=50),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('like_new', 'Like New')], max_length=10),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='parts_images', to='oman_app.autoaccessorypartimage'),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], default='cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='provide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_accessory_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='parts_videos', to='oman_app.autoaccessorypartvideo'),
        ),
        migrations.AlterField(
            model_name='autoaccessorypartimage',
            name='image',
            field=models.ImageField(upload_to='auto_accessory_parts/images/'),
        ),
        migrations.AlterField(
            model_name='autoaccessorypartvideo',
            name='video',
            field=models.FileField(upload_to='auto_accessory_parts/videos/'),
        ),
    ]
