# Generated by Django 5.2.4 on 2025-08-07 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0022_remove_autoaccessorypart_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplate',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='regions',
        ),
        migrations.AddField(
            model_name='numberplate',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
