# Generated by Django 5.2.4 on 2025-08-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0023_remove_numberplate_cities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quadbikes',
            old_name='type',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='quadbikes',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='quadbikes',
            name='rental_period',
        ),
    ]
