# Generated by Django 5.2.4 on 2025-08-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0024_rename_type_quadbikes_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='boat_subtype',
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(choices=[('boats', 'Boats'), ('yachts', 'Yachts'), ('jet_skis', 'Jet Skis'), ('canoes', 'Canoes'), ('kayaks', 'Kayaks'), ('paddle_boats', 'Paddle Boats'), ('other', 'Other')], default='boats', max_length=50, verbose_name='Boat Type'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20, verbose_name='Condition'),
        ),
    ]
