# Generated by Django 5.2.4 on 2025-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0025_remove_boat_boat_subtype_alter_boat_boat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='lister_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('dealer', 'Dealer')], default='dealer', max_length=10, verbose_name='Lister Type'),
        ),
    ]
