# Generated by Django 5.2.4 on 2025-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0026_boat_lister_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20, null=True),
        ),
    ]
