# Generated by Django 5.2.4 on 2025-08-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0027_boat_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='plate_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car')], max_length=20),
        ),
    ]
