# Generated by Django 5.2.4 on 2025-08-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0028_alter_numberplate_plate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
    ]
