# Generated by Django 5.2.4 on 2025-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0029_alter_numberplate_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkcar',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
    ]
