# Generated by Django 5.2.4 on 2025-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0030_junkcar_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkcar',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], default='cash', max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
