# Generated by Django 5.2.4 on 2025-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0031_junkcar_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoaccessorypart',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
    ]
