# Generated by Django 5.2.4 on 2025-08-17 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0032_autoaccessorypart_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='CoverVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='covers/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headsets/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsetVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='headsets/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SmartWatch/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='SmartWatch/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='TabletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Tablet/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TabletVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Tablet/videos/', verbose_name='Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='mobile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobiles', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('gold', 'Gold'), ('green', 'Green'), ('grey', 'Grey'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('pearl_white', 'Pearl White'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('rose_gold', 'Rose Gold'), ('silver', 'Silver'), ('turquoise', 'Turquoise'), ('white', 'White'), ('yellow', 'Yellow')], default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='mobile',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='mobile',
            name='provide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='mobile',
            name='year',
            field=models.CharField(default='2012', max_length=100, verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('charger', 'Charger'), ('sparepart', 'Spare Part'), ('accessory', 'Accessory')], max_length=20, verbose_name='Item Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessories/images/', verbose_name='Image')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='oman_app.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='accessories/videos/', verbose_name='Video')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='oman_app.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covers', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='cover', to='oman_app.coverimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='cover', to='oman_app.covervideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headsets', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headsets', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='headset', to='oman_app.headsetimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='headset', to='oman_app.headsetvideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('omantel', 'Omantel'), ('ooredoo', 'Ooredoo'), ('vodafone', 'Vodafone')], max_length=20, verbose_name='Mobile Operator')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilesims', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilesims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileSIMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobilesim/images/', verbose_name='Image')),
                ('mobilesim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='oman_app.mobilesim')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSIMVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='mobilesim/videos/', verbose_name='Video')),
                ('mobilesim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='oman_app.mobilesim')),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('description', models.TextField(verbose_name='Description')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartwatches', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartwatches', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='smartwatch', to='oman_app.smartwatchimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='smartwatch', to='oman_app.smartwatchvideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model_number', models.CharField(max_length=100, verbose_name='Model Number')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('year', models.CharField(max_length=100, verbose_name='Year of Manufacture')),
                ('color', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('gold', 'Gold'), ('green', 'Green'), ('grey', 'Grey'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('pearl_white', 'Pearl White'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('rose_gold', 'Rose Gold'), ('silver', 'Silver'), ('turquoise', 'Turquoise'), ('white', 'White'), ('yellow', 'Yellow')], max_length=20)),
                ('storage_capacity', models.CharField(max_length=20, verbose_name='Storage Capacity')),
                ('screen_size', models.CharField(blank=True, choices=[('5', '5 inch'), ('5.5', '5.5 inch'), ('6', '6 inch'), ('6.9', '6.9 inch'), ('7', '7 inch'), ('7.7', '7.7 inch'), ('7.9', '7.9 inch'), ('8', '8 inch'), ('8.4', '8.4 inch'), ('8.7', '8.7 inch'), ('8.9', '8.9 inch'), ('9.4', '9.4 inch'), ('9.7', '9.7 inch'), ('10', '10 inch'), ('10.1', '10.1 inch'), ('10.2', '10.2 inch'), ('10.4', '10.4 inch'), ('10.5', '10.5 inch'), ('10.8', '10.8 inch'), ('10.9', '10.9 inch'), ('10.95', '10.95 inch'), ('11', '11 inch'), ('11.6', '11.6 inch'), ('12', '12 inch'), ('12.2', '12.2 inch'), ('12.3', '12.3 inch'), ('12.4', '12.4 inch'), ('12.5', '12.5 inch'), ('12.9', '12.9 inch'), ('13.3', '13.3 inch'), ('14', '14 inch'), ('17.3', '17.3 inch'), ('18.4', '18.4 inch')], max_length=10, null=True, verbose_name='Screen Size (only for tablets)')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], max_length=10)),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablets', to='oman_app.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='tablet', to='oman_app.tabletimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='tablet', to='oman_app.tabletvideo', verbose_name='Videos')),
            ],
        ),
    ]
