# Generated by Django 5.2.4 on 2025-08-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0033_coverimage_covervideo_headsetimage_headsetvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='accompaniments',
            field=models.CharField(blank=True, choices=[('box', 'Original Box'), ('charger', 'Charger'), ('headset', 'Headset')], default='box', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], default='128GB', max_length=20),
        ),
    ]
