# Generated by Django 5.2.4 on 2025-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0035_remove_tablet_year_tablet_accompaniments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='age',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('0_1_year', '0-1 Year'), ('2_3_year', '2-3 Year'), ('more_than_3_year', 'More Than 3 Year')], default='brand_new', max_length=20, verbose_name='Age'),
        ),
    ]
