# Generated by Django 5.2.4 on 2025-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0036_tablet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartwatch',
            name='title',
            field=models.CharField(default='Apple brandnew white smartwatch', max_length=255, verbose_name='Title'),
        ),
    ]
