# Generated by Django 5.2.4 on 2025-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0037_smartwatch_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryimage',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='accessoryvideo',
            name='accessory',
        ),
        migrations.AddField(
            model_name='accessory',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='accessory', to='oman_app.accessoryimage', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='accessory', to='oman_app.accessoryvideo', verbose_name='Videos'),
        ),
        migrations.AlterField(
            model_name='accessoryimage',
            name='image',
            field=models.ImageField(upload_to='accessory/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='accessoryvideo',
            name='video',
            field=models.FileField(upload_to='accessory/videos/', verbose_name='Video'),
        ),
    ]
