# Generated by Django 5.1.1 on 2025-08-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0038_remove_accessoryimage_accessory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='company',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='status',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='nationality',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('non-citizen', 'Non-Citizen')], default='non-citizen', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='working_days',
            field=models.CharField(choices=[('1', '1 Days'), ('2', '2 Days'), ('3', '3 Days'), ('4', '4 Days'), ('5', '5 Days'), ('6', '6 Days'), ('7', '7 Days')], default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_required',
            field=models.CharField(choices=[('none', 'No Experience Required'), ('newbie', 'Newbie'), ('1-2', '1-2 Years'), ('3-5', '3-5 Years'), ('6-10', '6-10 Years'), ('11-15', '11-15 Years'), ('15+', '15+ Years')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='working_hours',
            field=models.CharField(choices=[('fixed', 'Fixed Working Hours'), ('shift', 'Shift'), ('hourly', 'Hourly')], default='fixed', max_length=20),
        ),
    ]
