# Generated by Django 5.2.4 on 2025-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0040_babyitemsimage_babyitemsvideo_booksimage_booksvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyvehicle',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
        migrations.AlterField(
            model_name='tiresandcaps',
            name='tire_type',
            field=models.CharField(choices=[('tyres', 'Tyres'), ('rims', 'Rims'), ('set_wheels_rims_tyres', 'Set of Wheels, Rims and Tyres'), ('automotive_caps', 'Automotive Caps')], max_length=50),
        ),
    ]
