# Generated by Django 5.2.4 on 2025-08-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0041_alter_heavyvehicle_rental_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessindustriallisting',
            name='condition',
            field=models.CharField(choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='excellent', max_length=50, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='businessindustriallisting',
            name='usage',
            field=models.CharField(choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal_usage', 'Normal Usage'), ('heavy_usage', 'Heavy Usage')], default='never_used', max_length=50, verbose_name='Usage'),
        ),
    ]
