# Generated by Django 5.2.4 on 2025-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0042_businessindustriallisting_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessindustriallisting',
            name='title',
            field=models.CharField(default='Business Title', max_length=255, verbose_name='Title'),
        ),
    ]
