# Generated by Django 5.2.4 on 2025-08-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0043_businessindustriallisting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessindustriallisting',
            name='title',
        ),
    ]
