# Generated by Django 5.1.1 on 2025-08-26 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0044_remove_businessindustriallisting_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AutoServices/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='AutoServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='AutoServices/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ConsultancyServices/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='ConsultancyServices/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='DomesticServices/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='DomesticServices/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='EventEntertainmentServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='EventEntertainmentServices/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='EventEntertainmentServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='EventEntertainmentServices/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancersServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Freelancers/images/')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancersServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Freelancers/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthWellbeingServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HealthWellbeingServices/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='HealthWellbeingServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='HealthWellbeingServices/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMaintenanceServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HomeMaintenance/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMaintenanceServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='HomeMaintenance/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='MoversServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Movers/images/')),
            ],
        ),
        migrations.CreateModel(
            name='MoversServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Movers/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='OtherServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_services/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OtherServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='other_services/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Restoration/images/')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Restoration/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='TutorsServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Tutors/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TutorsServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Tutors/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='WebComputerServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WebComputer/images/')),
            ],
        ),
        migrations.CreateModel(
            name='WebComputerServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='WebComputer/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='AutoServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('ac_electrical', 'Air Condition & Electrical Repairing'), ('body_detailing', 'Body Detailing'), ('car_repair', 'Car Repair'), ('car_service', 'Car Service'), ('car_wash', 'Car Wash'), ('others', 'Others'), ('roadside_assistance', 'Roadside Assistance'), ('tyre_change', 'Tyre Change')], max_length=50, verbose_name='Type of Service')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='auto_service', to='oman_app.autoserviceimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='auto_service', to='oman_app.autoservicevideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('business', 'Business Consultancy Services'), ('legal', 'Legal Consultancy Services'), ('financial', 'Loans & Financial Services'), ('translation', 'Translation Services'), ('visa', 'Visa Consultancy Services'), ('others', 'Other Consultancy Services')], max_length=50, verbose_name='Type of Consultancy Service')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultancy_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='consultancy_service', to='oman_app.consultancyserviceimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='consultancy_service', to='oman_app.consultancyservicevideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('childcare', 'Childcare & Nannies'), ('cooks', 'Cooks'), ('gardeners', 'Gardeners & Outdoor Services'), ('maids', 'Maids'), ('pool', 'Pool Maintenance')], max_length=50, verbose_name='Type of Domestic Service')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='domestic_service', to='oman_app.domesticserviceimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='domestic_service', to='oman_app.domesticservicevideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='EventEntertainmentServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('caterers', 'Caterers'), ('party_rentals', 'Party Rentals & Supplies'), ('photography', 'Photography & Videography')], max_length=50, verbose_name='Type of Event & Entertainment Service')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='event_service', to='oman_app.evententertainmentserviceimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='event_service', to='oman_app.evententertainmentservicevideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancersServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='freelancers_service', to='oman_app.freelancersserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='freelancers_service', to='oman_app.freelancersservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='HealthWellbeingServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('beauty_spa', 'Beauty & Spa Services'), ('counsellors', 'Counsellors & Therapists'), ('medical', 'Medical Services'), ('personal_trainers', 'Personal Trainers')], max_length=50, verbose_name='Type of Health & Wellbeing Service')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='health_service', to='oman_app.healthwellbeingserviceimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='health_service', to='oman_app.healthwellbeingservicevideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMaintenanceServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('ac', 'AC Maintenance & Repair'), ('alarm', 'Alarm & Security'), ('carpenters', 'Carpenters'), ('electricians', 'Electricians'), ('general', 'General Maintenance'), ('handyman', 'Handyman'), ('interior', 'Interior Design & Architects'), ('painters', 'Painters'), ('pest_control', 'Pest Control'), ('plumbers', 'Plumbers'), ('renovations', 'Renovations & General Contracting'), ('smart_home', 'Smart Home Services')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_maintenance_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='home_maintenance_service', to='oman_app.homemaintenanceserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_maintenance_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='home_maintenance_service', to='oman_app.homemaintenanceservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='MoversServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('deep_cleaning', 'Deep Cleaning & Disinfection Services'), ('movers_packers', 'Movers & Packers'), ('storage', 'Storage Services')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movers_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='movers_service', to='oman_app.moversserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movers_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='movers_service', to='oman_app.moversservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='OtherServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='other_service', to='oman_app.otherserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='other_service', to='oman_app.otherservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('electronic', 'Electronic Appliances Repair'), ('fridge', 'Fridge Repair'), ('furniture', 'Furniture & Sofa Repair'), ('it', 'IT Repair'), ('jewelry', 'Jewelry & Watches Repairs'), ('washing_machine', 'Washing Machine Repair')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='restoration_service', to='oman_app.restorationserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='restoration_service', to='oman_app.restorationservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='TutorsServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('arts_crafts', 'Arts & Crafts'), ('dance', 'Dance'), ('fitness_sport', 'Fitness and Sport'), ('languages', 'Languages'), ('music', 'Music'), ('others', 'Others'), ('professional_training', 'Professional Training Courses'), ('subject_tutors', 'Subject Tutors')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='tutors_service', to='oman_app.tutorsserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='tutors_service', to='oman_app.tutorsservicevideo')),
            ],
        ),
        migrations.CreateModel(
            name='WebComputerServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('graphic_web', 'Graphic & Web Designers'), ('it_services', 'IT Services'), ('media_video', 'Media & Video Editing'), ('website_app', 'Website & App Development')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_computer_services', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='web_computer_service', to='oman_app.webcomputerserviceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_computer_services', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='web_computer_service', to='oman_app.webcomputerservicevideo')),
            ],
        ),
    ]
