# Generated by Django 5.2.4 on 2025-08-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0045_autoserviceimage_autoservicevideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoservicelisting',
            name='price',
        ),
    ]
