# Generated by Django 5.2.4 on 2025-08-27 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0046_remove_autoservicelisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemaintenanceservicelisting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
