# Generated by Django 5.2.4 on 2025-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0048_moversservicelisting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancersservicelisting',
            name='service_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='remote', max_length=20),
        ),
    ]
