# Generated by Django 5.2.4 on 2025-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0049_freelancersservicelisting_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportslisting',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Applicable subcategory depending on chosen category', max_length=50, null=True),
        ),
    ]
