# Generated by Django 5.2.4 on 2025-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0051_alter_petlisting_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportslisting',
            name='age',
            field=models.CharField(blank=True, choices=[('0-12', '0-12 months'), ('13-24', '13-24 months'), ('25-36', '25-36 months'), ('37-48', '37-48 months'), ('4plus', 'More than 4 years')], default='13-24', max_length=10, null=True),
        ),
    ]
