# Generated by Django 5.2.4 on 2025-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0052_sportslisting_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicallisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_2_years', '1-2 years'), ('3_5_years', '3-5 years'), ('6_10_years', '6-10 years'), ('10_plus', '10+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musicallisting',
            name='condition_detail',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musicallisting',
            name='subcategory',
            field=models.CharField(blank=True, help_text="Specify if category is 'Other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musicallisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='musicallisting',
            name='category',
            field=models.CharField(choices=[('guitars', 'Guitars'), ('pianos', 'Pianos, Keyboards & Organs'), ('percussion', 'Percussion'), ('string', 'String Instruments'), ('wind', 'Wind Instruments'), ('dj_recording', 'DJ & Recording Equipment'), ('other', 'Other')], max_length=50),
        ),
    ]
