# Generated by Django 5.2.4 on 2025-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0053_musicallisting_age_musicallisting_condition_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyitemslisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='babyitemslisting',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='babyitemslisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookslisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookslisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('a_levels', 'A Levels / High School'), ('primary_school', 'Primary School'), ('secondary_school', 'Secondary School'), ('university', 'University'), ('business_science_tech', 'Business/Science/Technology'), ('cook_books', 'Cook Books'), ('history_biography', 'History/Biography'), ('how_to_books', 'How-To Books'), ('picture_books', 'Picture Books'), ('religious_books', 'Religious Books'), ('self_help', 'Self Help / Motivational Books'), ('sports_health', 'Sports/Health Books'), ('travel_books', 'Travel Books'), ('other_nonfiction', 'Other'), ('action_adventure', 'Action/Adventure'), ('classics', 'Classics'), ('fantasy_scifi', 'Fantasy/Sci Fi'), ('humor', 'Humor'), ('mystery_thriller', 'Mystery/Thriller'), ('romance', 'Romance'), ('other_fiction', 'Other'), ('coloring_activity', 'Coloring/Activity Books'), ('educational_books', 'Educational Books'), ('fiction_cb', 'Fiction'), ('nonfiction_cb', 'Nonfiction'), ('picture_popup_books', 'Picture/Pop Up Books'), ('other_cb', 'Other'), ('book_lights', 'Book Lights'), ('daily_planners', 'Daily Planners'), ('diaries_notebooks', 'Diaries/Note Books'), ('other_accessories', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookslisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collectiblelisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collectiblelisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dvdsmovieslisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dvdsmovieslisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dvdsmovieslisting',
            name='rating',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG-13'), ('R', 'R'), ('NC17', 'NC-17'), ('Unrated', 'Unrated'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dvdsmovieslisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('action_adventure', 'Action, Adventure'), ('animation', 'Animation'), ('children_family', 'Children & Family'), ('comedy', 'Comedy'), ('concert_music', 'Concert/Music'), ('documentary', 'Documentary Film'), ('drama', 'Drama'), ('horror', 'Horror'), ('mystery_suspense', 'Mystery/Suspense'), ('series', 'Series'), ('sports', 'Sports'), ('other_genre', 'Other Genre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dvdsmovieslisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musiclisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musiclisting',
            name='duration',
            field=models.CharField(blank=True, choices=[('album', 'Album'), ('ep', 'EP'), ('box_set', 'Box Set'), ('single', 'Single'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musiclisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('cds_classical', 'Classical'), ('cds_country', 'Country'), ('cds_jazz', 'Jazz'), ('cds_latin', 'Latin'), ('cds_metal', 'Metal'), ('cds_rnb_soul_funk', 'R&B / Soul / Funk'), ('cds_arabic', 'Arabic'), ('cds_rock_indie', 'Rock & Indie Rock'), ('cass_classical', 'Classical'), ('cass_country', 'Country'), ('cass_jazz', 'Jazz'), ('cass_latin', 'Latin'), ('cass_metal', 'Metal'), ('cass_rnb_soul_funk', 'R&B / Soul / Funk'), ('cass_arabic', 'Arabic'), ('cass_rock_indie', 'Rock & Indie Rock'), ('digital_classical', 'Classical'), ('digital_country', 'Country'), ('digital_jazz', 'Jazz'), ('digital_latin', 'Latin'), ('digital_metal', 'Metal'), ('digital_rnb_soul_funk', 'R&B / Soul / Funk'), ('digital_arabic', 'Arabic'), ('digital_rock_indie', 'Rock & Indie Rock')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musiclisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketvoucherlisting',
            name='number_of_tickets',
            field=models.CharField(blank=True, choices=[('single', 'Single Ticket'), ('pair', 'Pair Tickets'), ('3', '3 Tickets'), ('4', '4 Tickets'), ('4_plus', '4+ Tickets')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='babyitemslisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookslisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookslisting',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type / Hardcover/Paperback'),
        ),
        migrations.AlterField(
            model_name='collectiblelisting',
            name='category',
            field=models.CharField(choices=[('antiques', 'Antiques'), ('art', 'Art'), ('decorations', 'Decorations'), ('pens_writing_instruments', 'Pens & Writing Instruments'), ('memorabilia', 'Memorabilia'), ('rocks_fossils_artifacts', 'Rocks / Fossils / Artifacts'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collectiblelisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectiblelisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('antiquities', 'Antiquities'), ('books_maps', 'Books & Maps'), ('decorations_antiques', 'Decorations'), ('furniture', 'Furniture'), ('machines_tools', 'Machines, Instruments & Tools'), ('other_antiques', 'Other'), ('drawings', 'Drawings'), ('paintings', 'Paintings'), ('photography', 'Photography'), ('statues', 'Statues'), ('other_art', 'Other'), ('domestic_decorations', 'Domestic Decorations'), ('linens_textiles', 'Linens/Textiles'), ('outdoor_decoration', 'Outdoor Decoration'), ('wall_hangings', 'Wall Hangings'), ('other_decorations', 'Other'), ('calligraphy', 'Calligraphy'), ('pens', 'Pens'), ('sets', 'Sets'), ('typewriters', 'Typewriters'), ('other_pens', 'Other'), ('cultural_memorabilia', 'Cultural Memorabilia'), ('historical_memorabilia', 'Historical Memorabilia'), ('limited_edition_memorabilia', 'Limited Edition Memorabilia'), ('military_memorabilia', 'Military Memorabilia'), ('religious_memorabilia', 'Religious Memorabilia'), ('sports_memorabilia', 'Sports Memorabilia'), ('other_memorabilia', 'Other'), ('artifacts', 'Artifacts'), ('fossils', 'Fossils'), ('petrified_wood', 'Petrified Wood'), ('rocks_crystals_minerals', 'Rocks, Crystals & Minerals'), ('other_rocks', 'Other'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dvdsmovieslisting',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title / Type'),
        ),
        migrations.AlterField(
            model_name='musiclisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
    ]
