# Generated by Django 5.2.4 on 2025-08-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0054_babyitemslisting_age_babyitemslisting_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babyitemslisting',
            old_name='main_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='babyitemslisting',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
