# Generated by Django 5.2.4 on 2025-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0055_rename_main_category_babyitemslisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturehomegardenlisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='furniturehomegardenlisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gaminglisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gaminglisting',
            name='package',
            field=models.CharField(blank=True, choices=[('system_controllers', 'Gaming System + Controllers'), ('system_games', 'Gaming System + Games'), ('system_games_controllers', 'Gaming System + Games & Controllers'), ('system_only', 'Gaming System Only')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gaminglisting',
            name='rating',
            field=models.CharField(blank=True, choices=[('EC', 'Early Child'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teens'), ('M', 'Mature'), ('RP', 'Rating Pending')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gaminglisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='toyslisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years'), ('6_10_years', '6-10 Years'), ('10_plus', '10+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='toyslisting',
            name='usage',
            field=models.CharField(blank=True, choices=[('never_used', 'Never Used'), ('used_once', 'Used Once'), ('light_usage', 'Light Usage'), ('normal', 'Normal Usage'), ('heavy', 'Heavy Usage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='furniturehomegardenlisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gaminglisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gaminglisting',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toyslisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True),
        ),
    ]
