# Generated by Django 5.2.4 on 2025-09-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0056_furniturehomegardenlisting_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toyslisting',
            old_name='main_category',
            new_name='category',
        ),
    ]
