# Generated by Django 5.2.4 on 2025-09-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0057_rename_main_category_toyslisting_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniturehomegardenlisting',
            old_name='main_category',
            new_name='category',
        ),
    ]
