# Generated by Django 5.2.4 on 2025-09-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0059_cameraimage_cameravideo_clothingaccessoriesimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(choices=[('4 GB', '4GB'), ('8 GB', '8GB'), ('16 GB', '16GB'), ('32GB', '32GB'), ('64 GB', '64GB'), ('128 GB', '128GB'), ('256 GB', '256GB'), ('512 GB', '512GB'), ('1 TB', '1TB'), ('2 TB', '2TB')], default='128GB', max_length=20),
        ),
    ]
