# Generated by Django 5.2.4 on 2025-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0060_alter_mobile_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(choices=[('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], default='128GB', max_length=20),
        ),
    ]
