# Generated by Django 5.2.4 on 2025-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0061_alter_mobile_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], default='128GB', max_length=20),
        ),
    ]
