# Generated by Django 5.2.4 on 2025-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0062_alter_mobile_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Salary Range'),
            preserve_default=False,
        ),
    ]
