# Generated by Django 5.2.4 on 2025-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0063_alter_jobpost_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='number_of_vacancies',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='qualifications',
            field=models.CharField(choices=[('noschool', 'No Formal Education'), ('basic', 'Basic Education (Grades 1–10)'), ('secondary', 'General Secondary (Grades 11–12)'), ('vocational', 'Vocational / Technical Certificate'), ('diploma', 'Diploma (Higher College of Technology / Colleges of Applied Sciences)'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('phd', 'Doctorate (PhD)')], default='secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='working_days',
            field=models.CharField(choices=[('2', '2 days / week'), ('3', '3 days / week'), ('4', '4 days / week'), ('5', '5 days / week'), ('6', '6 days / week'), ('7', '7 days / week')], default='5', max_length=10),
        ),
    ]
