# Generated by Django 5.2.6 on 2025-10-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0064_alter_jobpost_number_of_vacancies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmetclothes',
            name='provide_delivery',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Provide Delivery?'),
        ),
        migrations.AddField(
            model_name='helmetclothes',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Item Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helmetclothes',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
