# Generated by Django 5.2.6 on 2025-10-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0065_helmetclothes_provide_delivery_helmetclothes_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='work_location',
        ),
    ]
