# Generated by Django 5.2.4 on 2025-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0066_remove_jobpost_cities_remove_jobpost_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportslisting',
            name='category',
            field=models.CharField(choices=[('cycling', 'Cycling'), ('exercise_equipment', 'Exercise Equipment'), ('water_sports', 'Water Sports'), ('camping_hiking', 'Camping & Hiking'), ('golf', 'Golf'), ('indoor_sports', 'Indoor Sports'), ('team_sports', 'Team Sports'), ('tennis_racquet', 'Tennis & Racquet Sports'), ('winter_sports', 'Winter Sports')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sportslisting',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
