# Generated by Django 5.2.6 on 2025-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0067_alter_sportslisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesim',
            name='operator',
            field=models.CharField(choices=[('omantel', 'Omantel'), ('ooredoo', 'Ooredoo'), ('vodafone', 'Vodafone Oman'), ('friendi', 'FRiENDi mobile'), ('renna', 'Renna Mobile'), ('redbull', 'RedBull MOBILE')], max_length=20, verbose_name='Mobile Operator'),
        ),
    ]
