# Generated by Django 5.2.6 on 2025-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0068_alter_mobilesim_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservicelisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Price'),
        ),
    ]
