# Generated by Django 5.2.6 on 2025-10-14 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0069_autoservicelisting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRepairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarRepairMaintenance/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='CarRepairVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='CarRepairMaintenance/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='CarRepairMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance_repair', 'Car Maintenance & Repair'), ('towing', 'Towing'), ('car_wash', 'Car Wash')], default='maintenance_repair', max_length=50, verbose_name='Service Category')),
                ('title', models.CharField(max_length=255, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Service Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_repair_maintenance', to='oman_app.cities')),
                ('images', models.ManyToManyField(blank=True, related_name='car_repair_maintenance', to='oman_app.carrepairimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_repair_maintenance', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='car_repair_maintenance', to='oman_app.carrepairvideo', verbose_name='Videos')),
            ],
            options={
                'verbose_name': 'Car Repair & Maintenance',
                'verbose_name_plural': 'Car Repair & Maintenance Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
