# Generated by Django 5.2.4 on 2025-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0070_carrepairimage_carrepairvideo_carrepairmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessindustriallisting',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
    ]
