# Generated by Django 5.2.4 on 2025-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0071_alter_businessindustriallisting_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralisting',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_apply', 'Do Not Apply')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancelisting',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_apply', 'Does Not Apply')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewelrylisting',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_apply', 'Does Not Apply')], max_length=10, null=True),
        ),
    ]
