# Generated by Django 5.2.4 on 2025-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0073_alter_electronicslisting_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappliancelisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('used', 'Used')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homeappliancelisting',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_apply', 'Do Not Apply')], max_length=10, null=True),
        ),
    ]
