# Generated by Django 5.2.4 on 2025-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0074_alter_homeappliancelisting_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingaccessorieslisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('flawless', 'Flawless'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('used', 'Used')], max_length=20, null=True),
        ),
    ]
