# Generated by Django 5.2.4 on 2025-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0075_alter_clothingaccessorieslisting_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelrylisting',
            name='warranty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_apply', 'Do Not Apply')], max_length=10, null=True),
        ),
    ]
