# Generated by Django 5.2.4 on 2025-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0076_alter_jewelrylisting_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicallisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_2 years', '1-2 years'), ('3_5 years', '3-5 years'), ('6_10 years', '6-10 years'), ('10_plus', '10+ years')], max_length=20, null=True),
        ),
    ]
