# Generated by Django 5.2.6 on 2025-10-27 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0077_alter_musicallisting_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='certification_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='date_obtained',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='end_date_education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='institution_location',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='project_duration',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='role',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='start_date_education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='summary',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseekers', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20, null=True, verbose_name='Commitment'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='cover_letter',
            field=models.TextField(default=1, verbose_name='Cover Letter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='current_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Company'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education_level',
            field=models.CharField(choices=[('noschool', 'No Formal Education'), ('basic', 'Basic Education (Grades 1–10)'), ('secondary', 'General Secondary (Grades 11–12)'), ('vocational', 'Vocational / Technical Certificate'), ('diploma', 'Diploma (Higher College of Technology / Colleges of Applied Sciences)'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('phd', 'Doctorate (PhD)')], default=1, max_length=20, verbose_name='Education Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.CharField(choices=[('negotiable', 'Negotiable'), ('less_than_2000', 'Less than 2000'), ('2000_3999', '2000-3999'), ('4000_5999', '4000-5999'), ('6000_7999', '6000-7999'), ('8000_11999', '8000-11999'), ('12000_19999', '12000-19999'), ('20000_plus', '20000+')], default=1, max_length=20, verbose_name='Expected Salary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='headline',
            field=models.CharField(default=1, max_length=255, verbose_name='Headline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='job_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekers', to='oman_app.jobcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='nationality',
            field=models.CharField(default=1, max_length=255, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='notice_period',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('less_than_2_weeks', 'Less than 2 Weeks'), ('one_month', 'One Month'), ('more_than_one_month', 'More than One Month')], default=1, max_length=20, verbose_name='Notice Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/', verbose_name='Upload CV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='visa_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('business', 'Business'), ('employment', 'Employment'), ('residence', 'Residence'), ('spouse', 'Spouse'), ('student', 'Student'), ('tourist', 'Tourist'), ('visit', 'Visit')], default=1, max_length=20, verbose_name='Visa Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_experience',
            field=models.CharField(choices=[('0_1', '0-1 years'), ('1_2', '1-2 years'), ('2_5', '2-5 years'), ('5_10', '5-10 years'), ('10_15', '10-15 years'), ('15_plus', '15+ years')], default=1, max_length=20, verbose_name='Work Experience'),
            preserve_default=False,
        ),
    ]
