# Generated by Django 5.2.6 on 2025-10-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0078_remove_jobseeker_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='oman_app.skill', verbose_name='Skills'),
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Upload CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oman_app.jobcategory')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='oman_app.jobseeker')),
                ('profile_skills', models.ManyToManyField(blank=True, related_name='jobseeker_profiles', to='oman_app.skill', verbose_name='Profile Skills')),
            ],
            options={
                'unique_together': {('jobseeker', 'job_category')},
            },
        ),
    ]
