# Generated by Django 5.2.6 on 2025-11-07 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0079_skill_remove_jobseeker_job_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingtraining',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='drivingtraining',
            name='regions',
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivingtraining', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivingtraining',
            name='location',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20, null=True, verbose_name='Commitment'),
        ),
    ]
