# Generated by Django 5.2.6 on 2025-11-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0080_remove_drivingtraining_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='foreign',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='foreign',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='fullfloors',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='fullfloors',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='land',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='land',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='office',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='office',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='showrooms',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='showrooms',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='suits',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='suits',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='supermarket',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='supermarket',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='wholebuilding',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='wholebuilding',
            name='regions',
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='complex',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complex', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='factory',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='foreign',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fullfloors', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='land',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='shared',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='suits',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suits', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supermarket', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='townhouse', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='villa',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villa', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='oman_app.cities'),
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholebuilding', to='oman_app.cities'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shared',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shared',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suits',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suits',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
