# Generated by Django 5.2.4 on 2025-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0083_alter_apartment_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='additional_amenities',
            field=models.ManyToManyField(related_name='apartments', to='oman_app.additionalamenities'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='main_amenities',
            field=models.ManyToManyField(related_name='apartments', to='oman_app.mainamenities'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='nearby_location',
            field=models.ManyToManyField(related_name='apartments', to='oman_app.nearbylocation'),
        ),
    ]
