# Generated by Django 5.2.4 on 2025-11-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0084_alter_apartment_additional_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1 Bath'), ('2', '2 Baths'), ('3', '3 Baths'), ('4', '4 Baths'), ('5', '5 Baths'), ('6+', '6+ Baths')], max_length=10, verbose_name='Number of Bathrooms'),
        ),
    ]
