# Generated by Django 5.2.4 on 2025-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0086_alter_villa_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('1_floor', '1st Floor'), ('2_floor', '2nd Floor'), ('3_floor', '3rd Floor'), ('4_floor', '4th Floor'), ('5_floor', '5th Floor'), ('6_floor', '6th Floor'), ('7_floor', '7th Floor'), ('8_floor', '8th Floor'), ('9_floor', '9th Floor'), ('10_floor', '10th Floor'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
    ]
