# Generated by Django 5.2.4 on 2025-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0087_alter_apartment_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='complex',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='staff',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
    ]
