# Generated by Django 5.2.4 on 2025-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0091_alter_farm_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1 Bed'), ('2', '2 Beds'), ('3', '3 Beds'), ('4', '4 Beds'), ('5', '5 Beds'), ('6+', '6+ Beds')], max_length=10, verbose_name='Number of Bedrooms'),
        ),
    ]
