# Generated by Django 5.2.6 on 2025-11-26 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0094_userprofileview_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[('0-499', '0–499 cc'), ('500-999', '500–999 cc'), ('1000-1499', '1000–1499 cc'), ('1500-1999', '1500–1999 cc'), ('2000-2499', '2000–2499 cc'), ('2500-2999', '2500–2999 cc'), ('3000-3999', '3000–3999 cc'), ('4000-4999', '4000–4999 cc'), ('5000-5999', '5000–5999 cc'), ('6000+', '6000+ cc')], max_length=20, null=True, verbose_name='Engine Capacity'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='kilometers',
            field=models.CharField(blank=True, choices=[('1000-9999', '1,000 - 9,999 km'), ('10000-19999', '10,000 - 19,999 km'), ('20000-29999', '20,000 - 29,999 km'), ('30000-39999', '30,000 - 39,999 km'), ('40000-49999', '40,000 - 49,999 km'), ('50000-59999', '50,000 - 59,999 km'), ('60000-69999', '60,000 - 69,999 km'), ('70000-79999', '70,000 - 79,999 km'), ('80000-89999', '80,000 - 89,999 km'), ('90000-99999', '90,000 - 99,999 km'), ('100000-119999', '100,000 - 119,999 km'), ('120000-139999', '120,000 - 139,999 km'), ('140000-159999', '140,000 - 159,999 km'), ('160000-179999', '160,000 - 179,999 km'), ('180000-199999', '180,000 - 199,999 km'), ('200000+', '200,000+ km')], max_length=20, null=True, verbose_name='Kilometers'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='seats',
            field=models.CharField(blank=True, choices=[('2', '2 Seats'), ('3', '3 Seats'), ('4', '4 Seats'), ('5', '5 Seats'), ('6', '6 Seats'), ('7', '7 Seats'), ('8', '8 Seats'), ('8+', '8+ Seats')], max_length=5, null=True, verbose_name='Number of Seats'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[('11-250', '11 – 250 cc'), ('250-499', '250 – 499 cc'), ('500-599', '500 – 599 cc'), ('600-749', '600 – 749 cc'), ('750-999', '750 – 999 cc'), ('1000+', '1000 cc and above')], max_length=20, null=True, verbose_name='Engine Capacity (cc)'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='kilometers',
            field=models.CharField(blank=True, choices=[('0-5k', '0 - 5,000 km'), ('5k-10k', '5,000 - 10,000 km'), ('10k-20k', '10,000 - 20,000 km'), ('20k-30k', '20,000 - 30,000 km'), ('30k-40k', '30,000 - 40,000 km'), ('40k-50k', '40,000 - 50,000 km'), ('50k-75k', '50,000 - 75,000 km'), ('75k-100k', '75,000 - 100,000 km'), ('100k-150k', '100,000 - 150,000 km'), ('150k-200k', '150,000 - 200,000 km'), ('200k+', '200,000 km and above')], max_length=20, null=True, verbose_name='Kilometers'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[('11-250', '11 – 250 cc'), ('250-499', '250 – 499 cc'), ('500-599', '500 – 599 cc'), ('600-749', '600 – 749 cc'), ('750-999', '750 – 999 cc'), ('1000+', '1000 cc and above')], max_length=20, null=True, verbose_name='Engine Capacity (cc)'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='kilometers',
            field=models.CharField(blank=True, choices=[('0-5k', '0 - 5,000 km'), ('5k-10k', '5,000 - 10,000 km'), ('10k-20k', '10,000 - 20,000 km'), ('20k-30k', '20,000 - 30,000 km'), ('30k-40k', '30,000 - 40,000 km'), ('40k-50k', '40,000 - 50,000 km'), ('50k-75k', '50,000 - 75,000 km'), ('75k-100k', '75,000 - 100,000 km'), ('100k-150k', '100,000 - 150,000 km'), ('150k-200k', '150,000 - 200,000 km'), ('200k+', '200,000 km and above')], max_length=20, null=True, verbose_name='Kilometers'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Manufacture'),
        ),
    ]
