# Generated by Django 5.2.6 on 2025-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0095_alter_automobile_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='horsepower',
            field=models.CharField(blank=True, choices=[('0-99', '0–99 HP'), ('100-199', '100–199 HP'), ('200-299', '200–299 HP'), ('300-399', '300–399 HP'), ('400+', '400+ HP')], max_length=20, null=True, verbose_name='Horsepower (HP)'),
        ),
    ]
