# Generated by Django 5.2.4 on 2025-12-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0096_alter_automobile_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good')], max_length=100, verbose_name='Condition'),
        ),
    ]
