# Generated by Django 5.2.4 on 2025-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0099_alter_cover_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent Condition'), ('used_good', 'Used - Good Condition')], max_length=100, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('damaged', 'Damaged'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good')], max_length=100, verbose_name='Condition'),
        ),
    ]
