# Generated by Django 5.2.4 on 2025-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0100_alter_accessory_condition_alter_mobile_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservicelisting',
            name='service_type',
            field=models.CharField(choices=[('laundry_services', 'Laundry & Dry Cleaning Services'), ('tailoring', 'Tailoring & Alterations'), ('event_planning', 'Event Planning & Coordination'), ('printing_services', 'Printing & Publishing Services'), ('logistics', 'Logistics & Delivery Services'), ('marketing', 'Marketing & Advertising Services'), ('carpet_cleaning', 'Carpet & Upholstery Cleaning'), ('elderly_care', 'Elderly Care Services'), ('travel_services', 'Travel & Tourism Services'), ('insurance_services', 'Insurance Services'), ('real_estate_services', 'Real Estate Services'), ('waste_management', 'Waste Management & Recycling'), ('solar_installation', 'Solar Panel Installation'), ('generator_services', 'Generator Services & Maintenance'), ('signage_services', 'Signage Services'), ('security_services', 'Security Guard Services'), ('artisan_crafts', 'Artisan & Craft Services'), ('equipment_rental', 'Equipment Rental Services'), ('landscaping', 'Landscaping Services'), ('language_services', 'Language Interpretation Services'), ('other', 'Other Specialized Services')], default='other', max_length=20),
        ),
    ]
