# Generated by Django 5.2.6 on 2025-12-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0101_otherservicelisting_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberplate',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadbikes',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scooter',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiresandcaps',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
    ]
