# Generated by Django 5.2.4 on 2025-12-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0102_automobile_title_drivingtraining_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='helmetclothes',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='junkcar',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='land',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='office',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
    ]
