# Generated by Django 5.2.4 on 2025-12-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0103_alter_apartment_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
    ]
