# Generated by Django 5.2.4 on 2025-12-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0104_alter_clinic_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='office',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready To Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
    ]
