# Generated by Django 5.2.6 on 2025-12-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0105_alter_cafe_property_alter_commercial_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_categories/'),
        ),
    ]
