# Generated by Django 5.2.6 on 2025-12-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0106_jobcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='age',
            field=models.CharField(blank=True, choices=[('0-12', '0-12 months'), ('13-24', '13-24 months'), ('25-36', '25-36 months'), ('37-48', '37-48 months'), ('4plus', 'More than 4 years')], default='13-24 Months', max_length=10, null=True),
        ),
    ]
