# Generated by Django 5.2.6 on 2025-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0107_alter_petlisting_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyitemslisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('car_seat_accessories', 'Car Seat Accessories'), ('infant_car_seats', 'Infant Car Seats'), ('jogging_strollers', 'Jogging Strollers'), ('pram_strollers', 'Pram Strollers'), ('standard_strollers', 'Standard Strollers'), ('stroller_accessories', 'Stroller Accessories'), ('toddler_car_seats', 'Toddler Car Seats'), ('travel_system_strollers', 'Travel System Strollers'), ('baby_dressers', 'Baby Dressers'), ('bassinets_cradles_rockers', 'Bassinets, Cradles & Rockers'), ('changing_tables', 'Changing Tables'), ('cribs', 'Cribs'), ('nursery_bedding', 'Nursery Bedding'), ('nursery_decor_accessories', 'Nursery Decor & Accessories'), ('nursery_furniture_sets', 'Nursery Furniture Sets'), ('backpacks_carriers', 'Backpacks & Carriers'), ('chairs', 'Chairs'), ('jumping_exercisers', 'Jumping Exercisers'), ('swings', 'Swings'), ('walkers', 'Walkers'), ('baby_food_processor', 'Baby Food Processor'), ('bibs', 'Bibs'), ('booster_high_chairs', 'Booster/High Chairs'), ('bottles', 'Bottles'), ('dishes_utensils', 'Dishes & Utensils'), ('nursing_pillows', 'Nursing Pillows'), ('pacifiers', 'Pacifiers'), ('baby_house_car_proofing', 'Baby House & Car Proofing'), ('baby_monitors', 'Baby Monitors'), ('baby_thermometers', 'Baby Thermometers'), ('locks_latches', 'Locks & Latches'), ('bath_tubs', 'Bath Tubs'), ('diaper_bins', 'Diaper Bins'), ('diapers_wipes', 'Diapers & Wipes'), ('lotions_powders_shampoos', 'Lotions, Powders & Shampoos'), ('potties', 'Potties'), ('educational_toys', 'Educational Toys'), ('soft_toys', 'Soft Toys'), ('activity_centers', 'Activity Centers'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
