# Generated by Django 5.2.6 on 2025-12-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0108_alter_babyitemslisting_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclisting',
            name='title',
            field=models.CharField(default='Vinyl', max_length=255, verbose_name='Title'),
        ),
    ]
