# Generated by Django 5.2.6 on 2026-01-01 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0109_musiclisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('electric', 'Electric')], max_length=20, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Year of Manufacture'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Year of Manufacture'),
        ),
    ]
