# Generated by Django 5.2.6 on 2026-01-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0110_scooter_fuel_type_alter_automobile_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkcar',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
