# Generated by Django 5.2.6 on 2026-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0111_alter_junkcar_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmetclothes',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
