# Generated by Django 5.2.6 on 2026-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0112_alter_helmetclothes_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
