# Generated by Django 5.2.6 on 2026-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0113_alter_autoaccessorypart_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkcar',
            name='condition',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('not_working', 'Not Working'), ('scrap', 'Scrap'), ('accident', 'Accident'), ('engine_problem', 'Engine Problem'), ('transmission_problem', 'Transmission Problem')], max_length=20, verbose_name='Condition'),
        ),
    ]
