# Generated by Django 5.2.6 on 2026-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0114_alter_junkcar_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Land Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Surface Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercial',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='land Area'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
