# Generated by Django 5.2.4 on 2026-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0115_commercial_surface_area_complex_surface_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
