# Generated by Django 5.2.4 on 2026-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0116_alter_automobile_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='babyitemslisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='bookslisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='collectiblelisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='computerlisting',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cover',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dvdsmovieslisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='furniturehomegardenlisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gaminglisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='headset',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='helmetclothes',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='junkcar',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='land',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobilesim',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='musicallisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='musiclisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='office',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sportslisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
    ]
