# Generated by Django 5.2.6 on 2026-01-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0117_alter_accessory_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='facade',
            field=models.CharField(blank=True, choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
    ]
