# Generated by Django 5.2.6 on 2026-01-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0118_alter_villa_facade_alter_villa_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sell', max_length=10, null=True),
        ),
    ]
