# Generated by Django 5.2.6 on 2026-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0119_alter_petlisting_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sale'), ('wanted', 'Wanted')], max_length=10, null=True),
        ),
    ]
