# Generated by Django 5.2.6 on 2026-01-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0120_alter_petlisting_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='accept_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='age',
            field=models.CharField(blank=True, choices=[('0-12', '0-12 months'), ('13-24', '13-24 months'), ('25-36', '25-36 months'), ('37-48', '37-48 months'), ('4plus', 'More than 4 years')], default='13-24', max_length=10, null=True),
        ),
    ]
