# Generated by Django 5.2.6 on 2026-01-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0121_alter_petlisting_accept_exchange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiclisting',
            old_name='type',
            new_name='music_type',
        ),
    ]
