# Generated by Django 5.2.6 on 2026-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0122_rename_type_musiclisting_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclisting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
