# Generated by Django 5.2.6 on 2026-01-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0123_alter_musiclisting_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiclisting',
            old_name='music_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='musiclisting',
            name='title',
            field=models.CharField(default='Vinyl', max_length=255, verbose_name='Title'),
        ),
    ]
