# Generated by Django 5.2.6 on 2026-01-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0124_rename_music_type_musiclisting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicallisting',
            name='age',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('1_2_years', '1-2 years'), ('3_5_years', '3-5 years'), ('6_10_years', '6-10 years'), ('10_plus', '10+ years')], max_length=20, null=True),
        ),
    ]
