# Generated by Django 5.2.6 on 2026-01-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0125_alter_musicallisting_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_admin_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Land Area (sq ft/m²)'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
