# Generated by Django 5.2.4 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0127_alter_motorcycle_kilometers_alter_scooter_kilometers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='kilometers',
            field=models.CharField(blank=True, choices=[('0-5k', '0 - 5,000 km'), ('5k-10k', '5,000 - 10,000 km'), ('10k-20k', '10,000 - 20,000 km'), ('20k-30k', '20,000 - 30,000 km'), ('30k-40k', '30,000 - 40,000 km'), ('40k-50k', '40,000 - 50,000 km'), ('50k-75k', '50,000 - 75,000 km'), ('75k-100k', '75,000 - 100,000 km'), ('100k-150k', '100,000 - 150,000 km'), ('150k-200k', '150,000 - 200,000 km'), ('200k+', '200,000 km and above')], max_length=20, null=True, verbose_name='Kilometers'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='kilometers',
            field=models.CharField(blank=True, choices=[('0-5k', '0 - 5,000 km'), ('5k-10k', '5,000 - 10,000 km'), ('10k-20k', '10,000 - 20,000 km'), ('20k-30k', '20,000 - 30,000 km'), ('30k-40k', '30,000 - 40,000 km'), ('40k-50k', '40,000 - 50,000 km'), ('50k-75k', '50,000 - 75,000 km'), ('75k-100k', '75,000 - 100,000 km'), ('100k-150k', '100,000 - 150,000 km'), ('150k-200k', '150,000 - 200,000 km'), ('200k+', '200,000 km and above')], max_length=20, null=True, verbose_name='Kilometers'),
        ),
    ]
