# Generated by Django 6.0.1 on 2026-02-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0128_alter_motorcycle_kilometers_alter_scooter_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='main_type',
            field=models.CharField(choices=[('trucks', 'Trucks'), ('buses', 'Buses'), ('forklifts', 'Forklifts'), ('trailers', 'Trailers'), ('cranes', 'Cranes'), ('tankers', 'Tankers'), ('parts_engines', 'Parts & Engines'), ('aircrafts', 'Aircrafts'), ('other', 'Other Vehicles')], default='trucks', max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='office',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='property',
            field=models.CharField(choices=[('complete', 'Ready to Occupy'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
    ]
