# Generated by Django 6.0.1 on 2026-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0129_mobile_title_alter_cafe_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
    ]
