# Generated by Django 6.0.1 on 2026-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0130_tablet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessindustriallisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computerlisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gaminglisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petlisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportslisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketvoucherlisting',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Listing Title'),
            preserve_default=False,
        ),
    ]
