# Generated by Django 6.0.1 on 2026-02-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oman_app', '0131_bookslisting_title_business_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_admin_chat',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
