# Generated by Django 6.0.1 on 2026-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0133_alter_chatmessage_options_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='object_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_admin_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
