# Generated by Django 6.0.1 on 2026-02-09 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0135_chatmessage_chat_session_id_chatmessage_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='usage_type',
            field=models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], default=1, max_length=20, verbose_name='Plate Usage Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='letter_arabic',
            field=models.CharField(max_length=10, verbose_name='Arabic Letter'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='letter_english',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only uppercase English letters (A–Z) are allowed.', regex='^[A-Z]+$')], verbose_name='English Letter'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sale'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='plate_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car')], max_length=20, verbose_name='Vehicle Type'),
        ),
    ]
