# Generated by Django 6.0.1 on 2026-02-16 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0136_numberplate_usage_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='oman_app_ch_chat_se_7f06b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='oman_app_ch_sender__82b6e2_idx',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_session_id',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='product_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session_id', 'timestamp'], name='oman_app_ch_chat_se_aa99d0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver'], name='oman_app_ch_sender__bab5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['product_id', 'product_type'], name='oman_app_ch_product_e63fcd_idx'),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_admin_chat',
        ),
    ]
