# Generated by Django 6.0.1 on 2026-02-16 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0137_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='oman_app_ch_chat_se_aa99d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='oman_app_ch_sender__bab5d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='oman_app_ch_product_e63fcd_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_admin_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session_id'], name='oman_app_ch_chat_se_7f06b0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', 'product_id', 'product_type'], name='oman_app_ch_sender__82b6e2_idx'),
        ),
    ]
