# Generated by Django 5.2.4 on 2026-02-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0138_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingtraining',
            name='trainer_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
