# Generated by Django 6.0.1 on 2026-02-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0140_chatmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('wanted', 'Wanted')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
