# Generated by Django 6.0.1 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0141_alter_numberplate_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
