# Generated by Django 6.0.1 on 2026-02-24 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0142_alter_numberplate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='letter_english',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only uppercase English letters (A–Z) are allowed.', regex='^[A-Z ]+$')], verbose_name='English Letter'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter up to 5 digits only.', regex='^\\d{1,5}$')], verbose_name='Plate Number'),
        ),
    ]
