# Generated by Django 6.0.1 on 2026-03-04 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oman_app', '0144_banner_blog_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view_product', 'Viewed Product'), ('view_profile', 'Viewed Profile'), ('add_favorite', 'Added to Favorites'), ('remove_favorite', 'Removed from Favorites'), ('report_product', 'Reported Product'), ('mark_sold', 'Marked Product as Sold'), ('create_product', 'Created Product'), ('edit_product', 'Edited Product'), ('delete_product', 'Deleted Product'), ('send_message', 'Sent Message'), ('receive_message', 'Received Message'), ('start_chat', 'Started Chat'), ('delete_message', 'Deleted Message'), ('block_user', 'Blocked User'), ('unblock_user', 'Unblocked User'), ('delete_chat', 'Deleted Chat'), ('follow_user', 'Followed User'), ('unfollow_user', 'Unfollowed User'), ('create_job', 'Created Job Post'), ('apply_job', 'Applied for Job'), ('approve_application', 'Approved Application'), ('reject_application', 'Rejected Application'), ('register_company', 'Registered Company'), ('update_company', 'Updated Company'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('register', 'Registered'), ('password_change', 'Changed Password'), ('update_profile', 'Updated Profile'), ('upload_image', 'Uploaded Image')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='oman_app_us_user_id_fd0d64_idx'), models.Index(fields=['activity_type', '-timestamp'], name='oman_app_us_activit_619a85_idx'), models.Index(fields=['timestamp'], name='oman_app_us_timesta_d5a651_idx')],
            },
        ),
    ]
