# Generated by Django 6.0.1 on 2026-03-04 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oman_app', '0145_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='oman_app_us_activit_619a85_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='oman_app_us_timesta_d5a651_idx',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='metadata',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('view', 'View'), ('favorite_add', 'Add to Favorites'), ('favorite_remove', 'Remove from Favorites'), ('chat_sent', 'Chat Message Sent'), ('chat_received', 'Chat Message Received'), ('report', 'Report Submitted'), ('mark_sold', 'Mark as Sold'), ('job_apply', 'Job Application'), ('job_post', 'Job Post Created'), ('company_register', 'Company Registration'), ('follow', 'Follow User'), ('unfollow', 'Unfollow User'), ('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('product_post', 'Product Posted'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='oman_app_us_activit_791d62_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['content_type', 'object_id'], name='oman_app_us_content_75670d_idx'),
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='description',
        ),
    ]
