# Generated by Django 6.0.1 on 2026-03-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0146_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivity',
            name='oman_app_us_user_id_fd0d64_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='oman_app_us_activit_791d62_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='oman_app_us_content_75670d_idx',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
