# Generated by Django 6.0.1 on 2026-03-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oman_app', '0148_customuser_chat_blocked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Hide Listing'), ('delete', 'Delete Listing'), ('warn', 'Warn User'), ('dismiss', 'Dismiss Report')], max_length=20)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='productreport',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Internal notes from moderator'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='productreport',
            index=models.Index(fields=['status', 'created_at'], name='oman_app_pr_status_2c9402_idx'),
        ),
        migrations.AddIndex(
            model_name='productreport',
            index=models.Index(fields=['content_type', 'object_id'], name='oman_app_pr_content_7d6ba6_idx'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='oman_app.productreport'),
        ),
    ]
