# Generated by Django 6.0.1 on 2026-03-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0149_moderationaction_alter_productreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationaction',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='moderationaction',
            name='report',
        ),
        migrations.AlterModelOptions(
            name='productreport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='productreport',
            name='oman_app_pr_status_2c9402_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreport',
            name='oman_app_pr_content_7d6ba6_idx',
        ),
        migrations.DeleteModel(
            name='ModerationAction',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='status',
        ),
    ]
