# Generated by Django 6.0.1 on 2026-03-05 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0150_remove_moderationaction_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='hide_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
