# Generated by Django 6.0.1 on 2026-03-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0151_chatmessage_hidden_at_chatmessage_hidden_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='hide_reason',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_hidden',
        ),
    ]
