# Generated by Django 6.0.1 on 2026-03-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0152_remove_chatmessage_hidden_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'User Management'), ('reports', 'Reports & Analytics'), ('settings', 'Settings'), ('content', 'Content Management'), ('motors', 'Motors Category'), ('real_estate', 'Real Estate Category'), ('mobiles', 'Mobiles & Tablets'), ('services', 'Services'), ('classifieds', 'Other Classifieds'), ('jobs', 'Jobs & Recruitment'), ('chat', 'Chat Moderation'), ('payments', 'Payments'), ('notifications', 'Notifications')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict, help_text='JSON field storing all permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this sub-admin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subadmins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-Admin',
                'verbose_name_plural': 'Sub-Admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubAdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('suspend', 'Suspend'), ('export', 'Export'), ('view', 'View'), ('permission_change', 'Permission Change'), ('status_change', 'Status Change')], max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='oman_app.subadmin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subadmin', '-created_at'], name='oman_app_su_subadmi_09df71_idx'), models.Index(fields=['action_type'], name='oman_app_su_action__c19de2_idx')],
            },
        ),
    ]
