# Generated by Django 6.0.1 on 2026-03-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0153_subadminpermission_subadmin_subadminactivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadmin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='subadminactivitylog',
            name='oman_app_su_subadmi_09df71_idx',
        ),
        migrations.RemoveIndex(
            model_name='subadminactivitylog',
            name='oman_app_su_action__c19de2_idx',
        ),
        migrations.DeleteModel(
            name='SubAdminPermission',
        ),
        migrations.RemoveField(
            model_name='subadminactivitylog',
            name='subadmin',
        ),
        migrations.RemoveField(
            model_name='subadminactivitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubAdmin',
        ),
        migrations.DeleteModel(
            name='SubAdminActivityLog',
        ),
    ]
