# Generated by Django 6.0.1 on 2026-03-06 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0154_remove_subadmin_created_by_remove_subadmin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_categories', models.BooleanField(default=False)),
                ('can_manage_listings', models.BooleanField(default=False)),
                ('can_manage_jobs', models.BooleanField(default=False)),
                ('can_manage_companies', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_advertisements', models.BooleanField(default=False)),
                ('can_manage_banners', models.BooleanField(default=False)),
                ('can_manage_faq', models.BooleanField(default=False)),
                ('can_manage_blog', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_regions', models.BooleanField(default=False)),
                ('can_manage_amenities', models.BooleanField(default=False)),
                ('can_manage_subadmins', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subadmins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubAdmin',
                'verbose_name_plural': 'SubAdmins',
            },
        ),
    ]
