# Generated by Django 6.0.1 on 2026-03-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0155_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdmin',
        ),
    ]
