# Generated by Django 6.0.1 on 2026-03-06 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0156_delete_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Permission name', max_length=100)),
                ('section', models.CharField(choices=[('real_estate', 'Real Estate Management'), ('motors', 'Motors Management'), ('mobiles', 'Mobiles & Tablets Management'), ('services', 'Services Management'), ('classifieds', 'Other Classifieds Management'), ('jobs', 'Jobs Management'), ('job_categories', 'Job Categories Management'), ('job_posts', 'Job Posts Management'), ('job_applications', 'Job Applications Management'), ('users', 'User Management'), ('user_reports', 'User Reports'), ('user_activity', 'User Activity Log'), ('categories', 'Categories Management'), ('subcategories', 'Subcategories Management'), ('regions', 'Regions Management'), ('governates', 'Governates Management'), ('districts', 'Districts Management'), ('cities', 'Cities Management'), ('amenities', 'Amenities Management'), ('ads_approval', 'Ads Approval'), ('featured_ads', 'Featured Ads'), ('reported_ads', 'Reported Ads'), ('analytics_view', 'View Analytics'), ('reports_export', 'Export Reports'), ('chat_monitor', 'Chat Monitoring'), ('support_chat', 'Support Chat'), ('payments_view', 'View Payments'), ('refunds_manage', 'Manage Refunds'), ('companies', 'Company Management'), ('company_approval', 'Company Approval')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_view', models.BooleanField(default=True, help_text='Can view this section')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit/update items')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete items')),
                ('can_approve', models.BooleanField(default=False, help_text='Can approve/reject items')),
                ('can_create', models.BooleanField(default=False, help_text='Can create new items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub-Admin Permission',
                'verbose_name_plural': 'Sub-Admin Permissions',
                'ordering': ['section'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('agent', 'Agent'), ('admin', 'Admin'), ('subadmin', 'Sub-Admin')], default='regular', max_length=10),
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this sub-admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subadmins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='subadmins', to='oman_app.subadminpermission')),
            ],
            options={
                'verbose_name': 'Sub-Admin',
                'verbose_name_plural': 'Sub-Admins',
                'ordering': ['-created_at'],
            },
        ),
    ]
