# Generated by Django 6.0.1 on 2026-03-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0157_subadminpermission_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('real_estate', 'Real Estate Management'), ('motors', 'Motors Management'), ('mobiles', 'Mobiles & Tablets Management'), ('services', 'Services Management'), ('classifieds', 'Other Classifieds Management'), ('jobs', 'Jobs Management'), ('job_categories', 'Job Categories Management'), ('job_posts', 'Job Posts Management'), ('job_applications', 'Job Applications Management'), ('users', 'User Management'), ('user_reports', 'User Reports'), ('user_activity', 'User Activity Log'), ('categories', 'Categories Management'), ('governates', 'Governates Management'), ('districts', 'Districts Management'), ('cities', 'Cities Management'), ('amenities', 'Amenities Management'), ('ads_approval', 'Ads Approval'), ('featured_ads', 'Featured Ads'), ('reported_ads', 'Reported Ads'), ('analytics_view', 'View Analytics'), ('reports_export', 'Export Reports'), ('chat_monitor', 'Chat Monitoring'), ('support_chat', 'Support Chat'), ('payments_view', 'View Payments'), ('refunds_manage', 'Manage Refunds'), ('companies', 'Company Management'), ('company_approval', 'Company Approval'), ('advertisement', 'Advertisement Management'), ('nearbylocation', 'Nearby Locations'), ('mainamenities', 'Main Amenities'), ('faq', 'FAQ Management'), ('blog', 'Blog Management')], max_length=50, unique=True),
        ),
    ]
