# Generated by Django 6.0.1 on 2026-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0159_alter_subadminpermission_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminpermission',
            name='is_admin_only',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='subadminpermission',
            name='can_view',
            field=models.BooleanField(default=False, help_text='Can view this section'),
        ),
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('payments', 'Payments Management'), ('payment_view', 'View Payments'), ('refund_manage', 'Manage Refunds'), ('subscriptions', 'Subscription Management'), ('commission', 'Commission Management'), ('analytics', 'Analytics Dashboard'), ('ad_analytics', 'Ad Analytics'), ('chat_analytics', 'Chat Analytics'), ('revenue_analytics', 'Revenue Analytics'), ('export_data', 'Export Data'), ('user_management_full', 'Full User Management'), ('user_delete', 'Delete Users'), ('user_suspend', 'Suspend Users'), ('user_approve', 'Approve Agents'), ('system_settings', 'System Settings'), ('backup', 'Backup & Restore'), ('logs', 'System Logs'), ('maintenance', 'Maintenance Mode'), ('category_management', 'Category Management'), ('subcategory_management', 'Subcategory Management'), ('admin_creation', 'Create Admins'), ('subadmin_management', 'Sub-admin Management'), ('permission_management', 'Permission Management'), ('developer_tools', 'Developer Tools'), ('api_keys', 'API Keys Management'), ('real_estate_view', 'Real Estate - View Only'), ('real_estate_manage', 'Real Estate - Full Management'), ('motors_view', 'Motors - View Only'), ('motors_manage', 'Motors - Full Management'), ('mobiles_view', 'Mobiles - View Only'), ('mobiles_manage', 'Mobiles - Full Management'), ('services_view', 'Services - View Only'), ('services_manage', 'Services - Full Management'), ('classifieds_view', 'Classifieds - View Only'), ('classifieds_manage', 'Classifieds - Full Management'), ('jobs_view', 'Jobs - View Only'), ('jobs_manage', 'Jobs - Full Management'), ('job_categories', 'Job Categories'), ('job_applications_view', 'View Job Applications'), ('companies_view', 'Companies - View Only'), ('companies_manage', 'Companies - Full Management'), ('governates_view', 'Governates - View Only'), ('governates_manage', 'Governates - Full Management'), ('districts_view', 'Districts - View Only'), ('districts_manage', 'Districts - Full Management'), ('cities_view', 'Cities - View Only'), ('cities_manage', 'Cities - Full Management'), ('regions_view', 'Regions - View Only'), ('regions_manage', 'Regions - Full Management'), ('amenities_view', 'Amenities - View Only'), ('amenities_manage', 'Amenities - Full Management'), ('faq_view', 'FAQ - View Only'), ('faq_manage', 'FAQ - Full Management'), ('blog_view', 'Blog - View Only'), ('blog_manage', 'Blog - Full Management'), ('banner_view', 'Banner - View Only'), ('banner_manage', 'Banner - Full Management'), ('ads_view', 'View All Ads'), ('ads_approve', 'Approve/Reject Ads'), ('reported_ads_view', 'View Reported Ads'), ('reported_ads_manage', 'Manage Reported Ads'), ('users_view', 'View Users Only'), ('user_reports_view', 'View User Reports'), ('user_activity_view', 'View User Activity'), ('chat_view', 'View Chats'), ('chat_moderate', 'Moderate Chats'), ('reports_view', 'View Reports')], max_length=50, unique=True),
        ),
    ]
