# Generated by Django 6.0.1 on 2026-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0160_subadminpermission_is_admin_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadminpermission',
            name='is_admin_only',
        ),
        migrations.AlterField(
            model_name='subadminpermission',
            name='can_view',
            field=models.BooleanField(default=True, help_text='Can view this section'),
        ),
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('real_estate', 'Real Estate Listings'), ('motors', 'Motors Listings'), ('mobiles', 'Mobiles & Tablets'), ('services', 'Services Listings'), ('classifieds', 'Other Classifieds'), ('jobs', 'Jobs Management'), ('job_categories', 'Job Categories'), ('job_posts', 'Job Posts'), ('job_applications', 'Job Applications'), ('companies', 'Company Management'), ('company_approval', 'Company Approval'), ('governates', 'Governates'), ('districts', 'Districts'), ('cities', 'Cities'), ('regions', 'Regions'), ('amenities', 'Amenities'), ('faq', 'FAQ Management'), ('blog', 'Blog Management'), ('banner', 'Banner Management'), ('ads_approval', 'Ads Approval'), ('reported_ads', 'Reported Ads'), ('users_view', 'View Users'), ('user_reports', 'User Reports'), ('user_activity', 'User Activity Log'), ('chat_monitor', 'Chat Monitoring')], max_length=50, unique=True),
        ),
    ]
