# Generated by Django 6.0.1 on 2026-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0161_remove_subadminpermission_is_admin_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('governates', 'Governates'), ('districts', 'Districts'), ('cities', 'Cities'), ('amenities', 'Amenities (Main, Additional, Nearby)'), ('interior_options', 'Interior Options'), ('exterior_options', 'Exterior Options'), ('technology_options', 'Technology Options'), ('faq', 'FAQ Management'), ('blog', 'Blog Management'), ('banner', 'Banner Management'), ('advertisement', 'Advertisement Management'), ('users_view', 'View Users')], max_length=50, unique=True),
        ),
    ]
