# Generated by Django 6.0.1 on 2026-03-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0162_alter_subadminpermission_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('governates', 'Governates'), ('districts', 'Districts'), ('cities', 'Cities'), ('amenities', 'Amenities (Main, Additional, Nearby)'), ('interior_options', 'Interior Options'), ('exterior_options', 'Exterior Options'), ('technology_options', 'Technology Options'), ('faq', 'FAQ Management'), ('blog', 'Blog Management'), ('banner', 'Banner Management'), ('advertisement', 'Advertisement Management'), ('companies', 'Company Management'), ('company_approval', 'Company Approval'), ('job_posts', 'Job Posts'), ('job_categories', 'Job Categories'), ('reported_ads', 'Reported Ads'), ('users_view', 'View Users'), ('user_reports', 'User Reports'), ('user_activity', 'User Activity Log')], max_length=50, unique=True),
        ),
    ]
