# Generated by Django 6.0.1 on 2026-03-09 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0164_alter_subadminpermission_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='action_taken',
            field=models.CharField(blank=True, help_text='What action was taken', max_length=100),
        ),
        migrations.AddField(
            model_name='productreport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about this report'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', max_length=20),
        ),
    ]
