# Generated by Django 6.0.1 on 2026-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0165_productreport_action_taken_productreport_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('motors', 'Motors'), ('real_estate', 'Real Estate'), ('job', 'Jobs'), ('other_classified', 'Other Classified'), ('mobiles', 'Mobiles'), ('services', 'Services')], default='motors', max_length=20),
        ),
    ]
