# Generated by Django 6.0.1 on 2026-03-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0166_alter_banner_options_banner_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('motors', 'Motors'), ('real_estate', 'Real Estate'), ('job', 'Jobs'), ('other_classified', 'Other Classified'), ('mobiles', 'Mobiles'), ('services', 'Services')], default='motors', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
