# Generated by Django 6.0.1 on 2026-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0167_alter_advertisement_options_advertisement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
