# Generated by Django 6.0.1 on 2026-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0168_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='mainamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='nearbylocation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Location Name'),
        ),
    ]
