# Generated by Django 6.0.1 on 2026-04-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0171_alter_additionalamenities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Amenity Name'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('motors', 'Motors'), ('real_estate', 'Real Estate'), ('job', 'Jobs'), ('other_classified', 'Other Classified'), ('mobiles', 'Mobiles'), ('services', 'Services')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Amenity Name'),
        ),
        migrations.AlterField(
            model_name='subadminpermission',
            name='section',
            field=models.CharField(choices=[('governates', 'Governates'), ('districts', 'Districts'), ('cities', 'Cities'), ('amenities', 'Amenities (Main, Additional, Nearby)'), ('interior_options', 'Interior Options'), ('exterior_options', 'Exterior Options'), ('technology_options', 'Technology Options'), ('faq', 'FAQ Management'), ('blog', 'Blog Management'), ('banner', 'Banner Management'), ('advertisement', 'Advertisement Management'), ('ads_approval_properties', 'Ads Approval - Properties (Land, Villa, Commercial, etc.)'), ('ads_approval_vehicles', 'Ads Approval - Vehicles (Cars, Motorcycles, Boats, etc.)'), ('ads_approval_electronics', 'Ads Approval - Electronics & Mobile (Phones, Tablets, Computers, etc.)'), ('ads_approval_classifieds', 'Ads Approval - Classifieds & Listings (Fashion, Toys, Books, etc.)'), ('ads_approval_services', 'Ads Approval - Services (Auto, Domestic, Tutoring, etc.)'), ('companies', 'Company Management'), ('company_approval', 'Company Approval'), ('job_posts', 'Job Posts'), ('job_categories', 'Job Categories'), ('reported_ads', 'Reported Ads'), ('users_view', 'View Users'), ('user_reports', 'User Reports'), ('user_activity', 'User Activity Log')], max_length=50, unique=True),
        ),
    ]
