# Generated by Django 6.0.1 on 2026-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0172_alter_additionalamenities_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainamenities',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Amenity Name'),
        ),
    ]
