# Generated by Django 6.0.1 on 2026-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0173_alter_mainamenities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Amenity Name'),
        ),
    ]
