# Generated by Django 6.0.1 on 2026-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0175_omandeallisting_omandealrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='omandealrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='omandealrequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='omandealrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='omandealrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='OmanDealListing',
        ),
        migrations.DeleteModel(
            name='OmanDealRequest',
        ),
    ]
