# Generated by Django 6.0.1 on 2026-04-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0177_land_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='post_type',
        ),
    ]
