# Generated by Django 6.0.1 on 2026-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0178_remove_land_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='post_type',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boost', 'Boost Post'), ('exclusive', 'Sell It / Exclusive')], default='normal', max_length=20, verbose_name='Post Type'),
        ),
    ]
