# Generated by Django 6.0.1 on 2026-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0180_remove_land_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='is_exclusive_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='listing_choice',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post'), ('exclusive', 'Exclusive/Sell it')], default='normal', max_length=20, null=True),
        ),
    ]
