# Generated by Django 6.0.1 on 2026-04-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0181_land_is_boosted_land_is_exclusive_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='is_boosted',
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_exclusive_request',
        ),
        migrations.RemoveField(
            model_name='land',
            name='listing_choice',
        ),
    ]
