# Generated by Django 6.0.1 on 2026-04-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0182_remove_land_is_boosted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='selling_option',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Post'), ('boost', 'Boost Promotion'), ('omandeal', 'OmanDeal Sell for You')], max_length=20, null=True, verbose_name='Selling Option'),
        ),
    ]
