# Generated by Django 6.0.1 on 2026-04-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0183_land_selling_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='selling_option',
        ),
    ]
