# Generated by Django 6.0.1 on 2026-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0184_remove_land_selling_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='land',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post'), ('exclusive', 'Exclusive Request')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
    ]
