# Generated by Django 6.0.1 on 2026-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0185_land_admin_verified_land_posting_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='exclusive_approved',
            field=models.BooleanField(default=False, verbose_name='Exclusive Approved'),
        ),
    ]
