# Generated by Django 6.0.1 on 2026-04-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0186_land_exclusive_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='exclusive_approved',
        ),
    ]
