# Generated by Django 6.0.1 on 2026-04-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0187_remove_land_exclusive_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
