# Generated by Django 6.0.1 on 2026-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0188_alter_land_posting_method_alter_land_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='villa',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
