# Generated by Django 6.0.1 on 2026-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0189_villa_admin_verified_villa_posting_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='complex',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='complex',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='factory',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='factory',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='farm',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='farm',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='foreign',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='foreign',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='office',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='office',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='shared',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='shared',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='shop',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='shop',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='staff',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='staff',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='suits',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='suits',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='tiresandcaps',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='admin_verified',
            field=models.BooleanField(default=False, verbose_name='Admin Verified for Exclusive'),
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='office',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='suits',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout'), ('exclusive', 'Exclusive'), ('pending_exclusive', 'Pending Exclusive')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
