# Generated by Django 6.0.1 on 2026-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0190_phoneotp_apartment_admin_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('motors', 'Motors'), ('real_estate', 'Real Estate'), ('job', 'Jobs'), ('other_classified', 'Other Classified'), ('mobiles', 'Mobiles'), ('services', 'Services')], default='home', max_length=20),
        ),
    ]
