# Generated by Django 6.0.1 on 2026-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0191_alter_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
