# Generated by Django 6.0.1 on 2026-04-14 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0193_alter_offers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='phone_number',
            field=models.CharField(help_text='Enter Omani number (e.g., 91234567)', max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Omani number (9 followed by 7 digits, e.g., 91234567)', regex='^9\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='offers',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter Omani WhatsApp number (e.g., 91234567)', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Omani number (9 followed by 7 digits, e.g., 91234567)', regex='^9\\d{7}$')]),
        ),
    ]
