# Generated by Django 6.0.1 on 2026-04-14 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0194_alter_offers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='phone_number',
            field=models.CharField(help_text='Enter 8-digit phone number (e.g., 91234567)', max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='offers',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter 8-digit WhatsApp number (optional)', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits', regex='^\\d{8}$')]),
        ),
    ]
