# Generated by Django 6.0.1 on 2026-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0197_businesscollaboration_privacypolicy_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoaccessorypart',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='boat',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='carrepairmaintenance',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='helmetclothes',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='junkcar',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='quadbikes',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
    ]
