# Generated by Django 6.0.1 on 2026-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0199_babyitemslisting_posting_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='cover',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='headset',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='mobilesim',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
    ]
