# Generated by Django 6.0.1 on 2026-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0200_accessory_posting_method_cover_posting_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='consultancyservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='domesticservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='evententertainmentservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='freelancersservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='healthwellbeingservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='homemaintenanceservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='moversservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='otherservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='restorationservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='tutorsservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
        migrations.AddField(
            model_name='webcomputerservicelisting',
            name='posting_method',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('boosted', 'Boosted Post')], default='normal', max_length=20, verbose_name='Posting Method'),
        ),
    ]
