# Generated by Django 6.0.1 on 2026-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0201_autoservicelisting_posting_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
