# Generated by Django 6.0.1 on 2026-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0202_alter_blog_options_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('motors', 'Motors'), ('real_estate', 'Real Estate'), ('other', 'Other'), ('job', 'Job'), ('mobiles_tablets', 'Mobiles and Tablets'), ('service', 'Service')], default='other', max_length=20),
        ),
    ]
