# Generated by Django 6.0.1 on 2026-04-22 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0203_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilesimvideo',
            name='mobilesim',
        ),
        migrations.AddField(
            model_name='mobilesim',
            name='oman_number',
            field=models.CharField(default=1, max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid 8-digit number.', regex='^\\d{8}$')], verbose_name='Oman Mobile Number'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MobileSIMImage',
        ),
        migrations.DeleteModel(
            name='MobileSIMVideo',
        ),
    ]
