# Generated by Django 6.0.1 on 2026-04-27 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oman_app', '0204_remove_mobilesimvideo_mobilesim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('original_product_model', models.CharField(max_length=100)),
                ('original_product_id', models.IntegerField()),
                ('admin_contact_phone', models.CharField(max_length=20)),
                ('admin_contact_email', models.EmailField(max_length=254)),
                ('admin_contact_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_contact_name', models.CharField(max_length=150)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_exclusive_listings', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_exclusive_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('original_product_model', 'original_product_id')},
            },
        ),
    ]
