# Generated by Django 6.0.1 on 2026-04-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0205_exclusivelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreign',
            name='admin_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AddField(
            model_name='foreign',
            name='admin_verified_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Verified By'),
        ),
    ]
