# Generated by Django 6.0.1 on 2026-04-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0206_foreign_admin_verified_at_foreign_admin_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreign',
            name='admin_verified_at',
        ),
        migrations.RemoveField(
            model_name='foreign',
            name='admin_verified_by',
        ),
        migrations.DeleteModel(
            name='ExclusiveListing',
        ),
    ]
