# Generated by Django 6.0.1 on 2026-05-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0207_remove_foreign_admin_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartwatch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartwatches', to='oman_app.district'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='governate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartwatches', to='oman_app.governate'),
        ),
    ]
