# Generated by Django 6.0.1 on 2026-05-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0208_smartwatch_district_smartwatch_governate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='governate',
        ),
    ]
