# Generated by Django 6.0.1 on 2026-05-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0214_smartwatch_district_smartwatch_governate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile', to='oman_app.district'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='governate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile', to='oman_app.governate'),
        ),
    ]
