# Generated by Django 6.0.1 on 2026-05-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0215_mobile_district_mobile_governate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='governate',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='governate',
        ),
    ]
