# Generated by Django 6.0.1 on 2026-05-13 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0217_aboutus_contactus_refundpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
