# Generated by Django 6.0.1 on 2026-05-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0218_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(),
        ),
    ]
