# Generated by Django 6.0.1 on 2026-05-14 04:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0219_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
