# Generated by Django 6.0.1 on 2026-05-16 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0222_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('listing', 'Listing Credits'), ('boost_individual', 'Individual Boost'), ('boost_bulk', 'Bulk Boost'), ('business', 'Business Package')], max_length=20, verbose_name='Package Type')),
                ('listing_credits', models.IntegerField(default=0, verbose_name='Number of Listing Credits')),
                ('boost_days', models.IntegerField(default=0, verbose_name='Boost Duration (Days)')),
                ('boost_posts_count', models.IntegerField(default=1, verbose_name='Number of Posts to Boost')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='Is Bulk Package')),
                ('price_omr', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price (OMR)')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='VAT %')),
                ('validity_days', models.IntegerField(default=45, verbose_name='Credit Validity (Days)')),
                ('is_business', models.BooleanField(default=False, verbose_name='Is Business Package')),
                ('business_duration_days', models.IntegerField(default=365, verbose_name='Business Package Duration (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features List')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Package',
                'verbose_name_plural': 'Credit Packages',
                'ordering': ['display_order', 'price_omr'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('expiry', 'Expiry'), ('bonus', 'Bonus')], max_length=20)),
                ('listing_credits_change', models.IntegerField(default=0, help_text='Positive = added, Negative = used')),
                ('boost_days_change', models.IntegerField(default=0, help_text='Positive = added, Negative = used')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('listing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('boost_duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='Paymob Transaction ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_omr', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount (OMR)')),
                ('vat_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Total Amount (incl. VAT)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_response', models.JSONField(blank=True, default=dict, verbose_name='Paymob Webhook Data')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_listings_total', models.IntegerField(default=30, verbose_name='Total Free Listings Allowed')),
                ('free_listings_used', models.IntegerField(default=0, verbose_name='Free Listings Used')),
                ('free_listings_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Free Tier Expiry')),
                ('purchased_listing_credits', models.IntegerField(default=0, verbose_name='Purchased Listing Credits Available')),
                ('boost_days_available', models.IntegerField(default=0, verbose_name='Boost Days Available')),
                ('is_business_user', models.BooleanField(default=False, verbose_name='Is Business Package User')),
                ('business_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Business Package Expiry')),
                ('total_listings_created', models.IntegerField(default=0, verbose_name='Total Listings Created')),
                ('total_boosts_used', models.IntegerField(default=0, verbose_name='Total Boosts Used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credits',
                'verbose_name_plural': 'User Credits',
            },
        ),
        migrations.CreateModel(
            name='BoostUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=100, verbose_name='Model Name')),
                ('listing_id', models.IntegerField(verbose_name='Listing ID')),
                ('boost_days', models.IntegerField(verbose_name='Boost Duration (Days)')),
                ('boost_days_used', models.IntegerField(default=0, verbose_name='Boost Days Used')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Boost Expiry Date')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boost Usage',
                'verbose_name_plural': 'Boost Usages',
                'indexes': [models.Index(fields=['listing_type', 'listing_id'], name='oman_app_bo_listing_d31ff7_idx'), models.Index(fields=['expires_at'], name='oman_app_bo_expires_e6bf7b_idx'), models.Index(fields=['is_active'], name='oman_app_bo_is_acti_f65b7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=100, verbose_name='Model Name')),
                ('listing_id', models.IntegerField(verbose_name='Listing ID')),
                ('credit_source', models.CharField(choices=[('free', 'Free Tier'), ('purchased', 'Purchased Credit')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('sold', 'Sold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expiry Date (45 days from creation)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Usage',
                'verbose_name_plural': 'Listing Usages',
                'indexes': [models.Index(fields=['listing_type', 'listing_id'], name='oman_app_li_listing_fa1565_idx'), models.Index(fields=['expires_at'], name='oman_app_li_expires_758aed_idx'), models.Index(fields=['user', 'status'], name='oman_app_li_user_id_3f9fcf_idx')],
            },
        ),
    ]
