# Generated by Django 6.0.1 on 2026-05-18 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0223_creditpackage_credittransaction_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAmountPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='25 OMR Credit Package', max_length=100)),
                ('amount_omr', models.DecimalField(decimal_places=3, default=25.0, max_digits=10)),
                ('listing_credits', models.IntegerField(default=5)),
                ('boost_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_omr', models.DecimalField(decimal_places=3, default=25.0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=3, default=1.25, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, default=26.25, max_digits=10)),
                ('payment_method', models.CharField(choices=[('paymob', 'Pay Online (Card)'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Credits Added'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Request',
                'verbose_name_plural': 'User Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
