# Generated by Django 6.0.1 on 2026-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0224_fixedamountpackage_userpaymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedamountpackage',
            name='boost_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixedamountpackage',
            name='listing_credits',
            field=models.IntegerField(default=25),
        ),
    ]
