# Generated by Django 6.0.1 on 2026-05-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0225_alter_fixedamountpackage_boost_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentrequest',
            name='pending_ad_data',
            field=models.TextField(blank=True, help_text='Stores ad data for publishing after payment', null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentrequest',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oman_app.creditpackage'),
        ),
    ]
