# Generated by Django 6.0.1 on 2026-06-04 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0228_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\S+$', 'Username cannot contain spaces.')]),
        ),
    ]
