# Generated by Django 6.0.1 on 2026-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0231_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Paymob Transaction ID'),
        ),
    ]
