# Generated by Django 6.0.1 on 2026-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0232_alter_paymenttransaction_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='regional_spec',
            field=models.CharField(choices=[('gcc', 'GCC'), ('gccoman', 'GCC(Oman)'), ('american', 'American'), ('canadian', 'Canadian'), ('euro', 'European'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese', 'Chinese'), ('other', 'Other')], default='gcc', max_length=20, verbose_name='Regional Specification'),
        ),
    ]
