# Generated by Django 6.0.1 on 2026-06-25 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0233_alter_automobile_regional_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=50)),
                ('listing_id', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('requires_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_type', 'listing_id'], name='oman_app_li_listing_af7c71_idx'), models.Index(fields=['user', 'is_read'], name='oman_app_li_user_id_0eae8e_idx')],
            },
        ),
    ]
