# Generated by Django 6.0.1 on 2026-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0234_listingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='autoservicelisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='businessindustriallisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='carrepairmaintenance',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='collectiblelisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='computerlisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='consultancyservicelisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='domesticservicelisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='drivingtraining',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='evententertainmentservicelisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='gaminglisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='headset',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='healthwellbeingservicelisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='helmetclothes',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='junkcar',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='lostfoundlisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='mobilesim',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='musicallisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quadbikes',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='sportscar',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sportslisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='suits',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='ticketvoucherlisting',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='toys',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Property Description'),
        ),
    ]
