# Generated by Django 6.0.1 on 2026-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0235_alter_accessory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_exclusive_contact',
            field=models.BooleanField(default=False, help_text="This account's contact details show on all approved exclusive listings."),
        ),
    ]
